#!/bin/bash -e
#Going to Home and declaring variables
cd
nam=""
what=apt
clear
#Set title
mytitle="Helen ~ 0.1.9"
echo -e '\033]2;'$mytitle'\007'
#Checking requirements
chk () {
    PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $nam|grep "install ok installed")
    echo "Checking for "$nam": " $PKG_OK
    if [ "" == "$PKG_OK" ]; then
        echo "No "$nam". Setting up "$nam"..."
        sudo apt install $nam -y
        sleep 1
        clear
    else
        echo $nam" is installed already."
        sleep 1
    fi
    }
nam=whiptail
chk
nam=dialog
chk
nam=software-properties-common
chk
nam=git
chk
#Defining functions
    promptDialogSpec () {   #Feedback for user (for func.s)
        clear
        $nam
        clear
        echo 'Done!'
        sleep 1.5
        }
    promptDialog () {   #Same.. Just for single apps from repo or snap
        clear
	    if [[ $what == "snap" ]]
		then
		    echo 'Installing '$nam'...'
		    eval sudo $what install $nam --classic $mut
		    clear
		    echo 'Done!'
        else
            echo 'Installing '$nam'...'
		    eval sudo $what install $nam -y $mut
		    clear
		    echo 'Done!'
		fi
		sleep 1.5
        }
    timsIns () {    #Timeshift
        sleep 0.5
        echo 'Installing timeshift...'
        eval sudo add-apt-repository -y ppa:teejee2008/ppa $mut
        eval sudo apt update $mut
        eval sudo apt install timeshift -y $mut
        }
    aptFast () {    #Apt-fast
        sleep 0.5
        echo 'Installing apt-fast...'
        eval sudo add-apt-repository -y ppa:apt-fast/stable $mut
        eval sudo apt update $mut
        eval sudo apt install apt-fast -y $mut
        }
    operaInstall () {   #Opera
        echo 'Installing Opera from Opera website...'
        eval wget https://download1.operacdn.com/pub/opera/desktop/57.0.3098.110/linux/opera-stable_57.0.3098.110_amd64.deb $mut
        eval sudo dpkg -i opera-stable_57.0.3098.110_amd64.deb $mut
        eval sudo apt update $mut
        eval sudo rm opera-stable_57.0.3098.110_amd64.deb $mut 
        }
    gesturesSetup () {  #Libinput gestures + GUI + xdotool
        echo 'Installing xdotool and wmctrl...'
        eval sudo apt install xdotool wmctrl -y $mut
        echo 'Done!'
        echo 'Installing libinput-tools...'
        eval sudo apt install libinput-tools -y $mut
        echo 'Done!'
        echo 'Setting input permisson for gestures...'
        eval sudo gpasswd -a $USER input $mut
        echo 'Done! ATTENTION!! You need to reboot to apply this operation!'
        sleep 1
        echo 'Cloning libinput gestures and gestures GUI from github...'
        eval git clone https://github.com/bulletmark/libinput-gestures.git $mut
        eval git clone https://gitlab.com/cunidev/gestures $mut
        echo 'Done!'
        echo 'Building packages...'
        eval cd libinput-gestures $mut
        eval sudo ./libinput-gestures-setup install $mut
        eval cd $mut
        eval cd gestures $mut
        eval sudo python3 setup.py install $mut
        eval cd $mut
        eval sudo rm -rf libinput-gestures $mut
        eval sudo rm -rf gestures $mut
        }
    wpsInstall () { #WPS office
        echo 'Downloading and installing WPS Office and WPS Office symbols (it takes around 7 min)...'
        eval wget http://kdl.cc.ksosoft.com/wps-community/download/6757/wps-office_10.1.0.6757_amd64.deb $mut
        eval wget https://github.com/IamDH4/ttf-wps-fonts/archive/master.zip $mut
        eval sudo dpkg -i wps-office_10.1.0.6757_amd64.deb $mut
        eval sudo rm wps-office_10.1.0.6757_amd64.deb $mut
        eval unzip master.zip $mut
        eval cd ttf-wps-fonts-master $mut
        eval bash install.sh $mut
        eval cd $mut
        eval sudo rm -rf ttf-wps-fonts-master $mut
        eval sudo rm master.zip $mut
        }
    woeIns () {
        clear
        echo "Installing WoeUsb..."
        sleep 1
        sudo add-apt-repository ppa:nilarimogard/webupd8 -y
        sudo apt update -y
        sudo apt install woeusb -y
        }
    tweakIns () { #Elementary-tweaks
        sleep 0.5
        echo 'Installing elementary tweaks...'
        eval sudo add-apt-repository -y ppa:philip.scott/elementary-tweaks $mut
        eval sudo apt update $mut
        eval sudo apt install elementary-tweaks -y $mut
        }
    adIns () {  #0AD
        sleep 0.5
        echo 'Installing 0ad from 0ad repository... This will take a while, please be patient...'
        eval sudo add-apt-repository -y ppa:wfg/0ad $mut
        eval sudo apt-get update $mut
        eval sudo apt-get install 0ad -y $mut
        }
    rebooter () {   #Rebboot confirmation
        clear
        if (whiptail --title "Reboot" --yesno "Do you really want to reboot?" 8 78); then
            systemctl reboot
        else
            echo "Ok, system won't reboot now."
            sleep 1
            clear
            no1
        fi
        }
    updater () {    #Update system
        echo 'Updating system...'
        eval sudo apt full-upgrade -y $mut
        echo 'Done!'
        }
    esEggs () {
            #Multichoice menu (Eastereggs)
            cmd=(whiptail --title "Selection menu" --separate-output --checklist "Select options:" 40 85 32)
            options=(1 "cmatrix" off    # Selection menu 3.5 using 'whiptail'
                     2 "sl" off
                     3 "boxes" off
                     4 "Check the weather from terminal" off
                     5 "Download (non-copyright only) videos from youtube with your terminal" off
                     6 "Play Sudoku in terminal" off
                     7 "Text to ASCII in terminal" off
                     8 "Make your terminal fancy!" off
                     9 "There are animals in the terminal!" off
                    10 "Do ypu know your fortune?" off)
            choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
            clear
            what=apt
            for choice in $choices
            do
                case $choice in
                    1)
                        nam=cmatrix
                        promptDialog
                        cmatrix
                        esEggs
                        ;;
                    2)
                        nam=sl
                        promptDialog
                        sl
                        esEggs
                        ;;
                    3)
                        nam=boxes
                        promptDialog
                        clear
                        echo "I am a dog :D" | boxes -d dog -a c
                        echo ""
                        read -p "Press enter to continue..."
                        esEggs
                        ;;
                    4)
                        clear
                        curl wttr.in
                        echo ""
                        read -p "Press enter to continue..."
                        esEggs
                        ;;
                    5)
                        nam=youtube-dl
                        promptDialog
                        esEggs
                        ;;
                    6)
                        nam=nudoku
                        promptDialog
                        nudoku
                        esEggs
                        ;;
                    7)
                        nam=figlet
                        promptDialog
                        clear
                        read -p "Write here something: " userText   
                        echo $userText | figlet
                        echo ""
                        read -p "Press enter to continue..."
                        esEggs
                        ;;
                    8)
                        nam=lolcat
                        promptDialog
                        clear
                        echo ">>>>>>>>>>>>>>>>>>>>>>> It's so colorful!! <<<<<<<<<<<<<<<<<<<<<<<<" | lolcat
                        echo ""
                        read -p "Press enter to continue..." | lolcat
                        esEggs
                        ;;
                    9)
                        nam=cowsay
                        promptDialog
                        clear
                        cowsay -f dragon "Run for cover, I feel a sneeze coming on!"
                        echo ""
                        read -p "Press enter to continue..."
                        esEggs
                        ;;
                   10)
                        nam=fortune-mod
                        promptDialog
                        fortune
                        ;;
                esac
            done
           }
    all () {
        if (whiptail --title "Install all" --yesno "Do you really want to install all packages?" 8 78); then
            whiptail --title "These operations would take effect (Press Esc to abort) : " --msgbox "snapd libreoffice libreoffice-gtk* git python3 python3-setuptools python3-gi python-gobject python3-pip mesa-utils wine-stable software-properties-common steam-installer virtualbox gparted dconf-editor ubuntu-restricted-extras libavcodec-extra flashplugin-installer pepperflashplugin-nonfree unace rar unrar p7zip-rar p7zip sharutils uudeview mpack arj cabextract lzip lunzip audacity deja-dup screenfetch apt-fast opera-stable gestures timeshift 0ad wpsoffice woeusb || update & restart" 15 85
            sudo apt install snapd libreoffice libreoffice-gtk* git python3 python3-setuptools python3-gi python-gobject python3-pip mesa-utils wine-stable software-properties-common steam-installer virtualbox gparted dconf-editor ubuntu-restricted-extras libavcodec-extra flashplugin-installer pepperflashplugin-nonfree unace rar unrar p7zip-rar p7zip sharutils uudeview mpack arj cabextract lzip lunzip audacity deja-dup screenfetch -y $mut
            sudo snap install skype vscode --classic $mut
            aptFast
            operaInstall
            gesturesSetup
            timsIns
            adIns
            wpsInstall
            woeIns
            updater
            rebooter
        else
            echo "Ok, going back to home..."
            sleep 1
            clear
            no1
        fi
        }
    adv () {
                #Multichoice menu (selection)
                cmd=(whiptail --title "Selection menu" --separate-output --checklist "Select options:" 40 50 32)
                options=(1 "Snapd" off    # Selection menu 3.5 using 'whiptail'
                         2 "Libreoffice" off
                         3 "Git" off
                         4 "python3" off
                         5 "mesa utils" off
                         6 "Wine" off
                         7 "software-properties-common" off
                         8 "Opera browser" off
                         9 "Steam" off
                         10 "Virtualbox" off
                         11 "GParted" off
                         12 "Dconf Editor" off
                         13 "Additional audio codecs" off
                         14 "Flash player support for browsers" off
                         15 "Archive management tools" off
                         16 "Audacity" off
                         17 "Déja dup" off
                         18 "Touchpad gestures" off
                         19 "Skype" off
                         20 "Visualstudio Code" off
                         21 "Screenfetch" off
                         22 "Timeshift" off
                         23 "Apt-fast" off
                         24 "WPS Office" off
                         25 "WoeUSB" off
                         26 "0 A.D." off
                         98 "Upgrade system" off
                         99 "Reboot after operation" off)
                choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
                clear
                for choice in $choices
                do
                    case $choice in
                        1)
                            nam=aptFast
                            promptDialogSpec
                            ;;
                        2)
                            nam='libreoffice libreoffice-gtk*'
                            promptDialog
                            ;;
                        3)
                            nam=git
                            promptDialog
                            ;;
                        4)
                            nam='python3 python3-setuptools python3-gi python-gobject python3-pip'
                            promptDialog
                            ;;
                        5)
                            nam=mesa-utils
                            promptDialog
                            ;;
                        6)
                            nam=wine-stable
                            promptDialog
                            ;;
                        7)
                            nam=software-properties-common
                            promptDialog
                            ;;
                        8)
                            nam=operaInstall
                            promptDialogSpec
                            ;;
                        9)
                            nam=steam-installer
                            promptDialog
                            ;;
                        10)
                            nam=virtualbox
                            promptDialog
                            ;;
                        11)
                            nam=gparted
                            promptDialog
                            ;;
                        12)
                            nam=dconf-editor
                            promptDialog
                            ;;
                        13)
                            nam='ubuntu-restricted-extras libavcodec-extra'
                            promptDialog
                            ;;
                        14)
                            nam='flashplugin-installer pepperflashplugin-nonfree'
                            promptDialog
                            ;;
                        15)
                            nam='unace rar unrar p7zip-rar p7zip sharutils uudeview mpack arj cabextract lzip lunzip'
                            promptDialog
                            ;;
                        16)
                            nam=audacity
                            promptDialog
                            ;;
                        17)
                            nam=deja-dup
                            promptDialog
                            ;;
                        18)
                            nam=gesturesSetup
                            promptDialogSpec
                            ;;
                        19)
                            what=snap
                            nam=skype
                            promptDialog
                            ;;
                        20)
                            what=snap
                            nam=vscode
                            promptDialog
                            ;;
                        21)
                            what=apt
                            nam=screenfetch
                            promptDialog
                            ;;
                        22)
                            nam=timsIns
                            promptDialogSpec
                            ;;
                        23)
                            nam=aptFast
                            promptDialogSpec
                            ;;
                        24)
                            nam=wpsInstall
                            promptDialogSpec
                            ;;
                        25)
                            nam=woeIns
                            promptDialogSpec
                            ;;
                        26)
                            nam=adIns
                            promptDialogSpec
                            ;;
                        98)
                            updater
                            ;;
                        99)
                            rebooter
                            ;;
                    esac
                done
                }
#Selection menu No. 1
no1 () {
    CMD=(whiptail --title "Welcome "$USER"!" --menu "Choose one of the following options:" 15 40 4)
    OPTIONS=(1 "Install everything (Simple)"
             2 "Select what to install (Advanced)"
             3 "Easter eggs selection"
             4 "About")
    CHOICES=$("${CMD[@]}" "${OPTIONS[@]}" 2>&1 >/dev/tty)
    clear
    case $CHOICES in
            1)
                all
                ;;
            2)
                adv
                ;;
            3)
                esEggs
                ;;
            4)
                #Intro screen
                dialog --title "About" --msgbox "       

                                        
                           | |  | |                   
                           | |__| | ___| | ___ _ __  
                           |  __  |/ _ \ |/ _ \ '_ \ 
                           | |  | |  __/ |  __/ | | |
                           |_|  |_|\___|_|\___|_| |_|
                                           
                                           

                Version 0.1.9

                Dániel Kolozsi

 ================================================================================

          Copyright (C) [2018] [Dániel Kolozsi]

          This program is free software: you can redistribute it and/or modify
          it under the terms of the GNU General Public License as published by
          the Free Software Foundation, either version 3 of the License, or
          (at your option) any later version.

          This program is distributed in the hope that it will be useful,
          but WITHOUT ANY WARRANTY; without even the implied warranty of
          MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
          GNU General Public License for more details.

          You should have received a copy of the GNU General Public License
          along with this program.  If not, see <https://www.gnu.org/licenses/>.

 ================================================================================

          Changes (09.03.2019):

              ~ Fixed bugs
              ~ Added required package checking
              ~ Added confirmation dialog to simple mode
              ~ Converted some 'in-terminal' operation to whiptail boxes
              ~ Added some new packages
              " 160 85
                clear
                no1
                ;;
    esac
    }
no1
